### ISSUE TITLE
Reminder for EP

### ISSUE THREAD

**Issue by NavidHjzn** [RomainGoussault/Deepov#19]
TODO
get EP from FEN
implement EP in pawnPseudoLegalMoves
implement EP in executeMove

**Comment by RomainGoussault** [comment]
And undo move

**Comment by NavidHjzn** [comment]
of course ty

**Comment by NavidHjzn** [comment]
is EP needed attacked positions ?

**Comment by RomainGoussault** [comment]
no

**Comment by NavidHjzn** [comment]
maybe for the IA

**Comment by RomainGoussault** [comment]
ah yeah, maybe

**Comment by RomainGoussault** [comment]
TODO: write test ;)

**Comment by RomainGoussault** [comment]
TODO: read En Passan state from FEN

**Comment by RomainGoussault** [comment]
Note: I think Perft(5) should work with enPassant working. Because it does not need Castling nor Promotion
