### ISSUE TITLE
Mate in one not found..

### ISSUE THREAD

**Issue by RomainGoussault** [RomainGoussault/Deepov#33]
Following position:
8/3R4/3p4/3P4/1K4Q1/8/7k/8 w - - 97 104

If white moves the rook it's a win. But Deepov prefers to move the King.

Sample code to test:

	MagicMoves::initmagicmoves();
	Tables::init();

	std::shared_ptr<Board> sp = std::shared_ptr<Board>(new Board("8/3R4/3p4/3P4/1K4Q1/8/7k/8 w - - 97 104"));
	Search search(sp);
	search.negaMaxRoot(4);
	Move move = search.myBestMove;

	std::cout << *sp << std::endl;
	std::cout << move.toShortString()  << std::endl;

**Comment by NavidHjzn** [comment]
Try negaMaxRoot(1). If it works, can we stop the iterative deepening when a mate is found ?

**Comment by NavidHjzn** [comment]
Deepov = noob anyway

**Comment by RomainGoussault** [comment]
negaMaxRoot(1) does not work because we don't check if black is in check after white's move

**Comment by RomainGoussault** [comment]
negaMaxRoot(2) and negaMaxRoot(3) work though..

**Comment by NavidHjzn** [comment]
Deepov prefers the mate in 2 somehow.

**Comment by RomainGoussault** [comment]
fixed
