### ISSUE TITLE
Windows 32/64 bit ?

### ISSUE THREAD

**Issue by yellow-panther** [RomainGoussault/Deepov#43]
il manque encore d´un (fichier) binaire pour Windows 32-64 bit!
cf http://talkchess.com/forum/viewtopic.php?topic_view=threads&p=675681&t=60511
une contribution de Günther Simon http://www.rwbc-chess.de
l´évaluation du programme Deepov aux points Elo (=rating) est inconnue

**Comment by RomainGoussault** [comment]
La release 0.4 avec les fichiers binaires pour Windows arrive bientôt (qq semaines)
