### ISSUE TITLE
Deepov 0.4.1 pour Macintosh de Joshua Pettus

### ISSUE THREAD

**Issue by ChessGUI** [RomainGoussault/Deepov#47]
il a créé un fichier compilé v0.4.1 ici: https://www.dropbox.com/s/930x0mbrrvcwct2/Deepov-0.4.1%20OSX%2010.7%2B.zip?dl=0 (lien de téléchargement), cf.
**Computer Chess Wiki - Macintosh Engine List**
http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:macintosh_engine_list

**Comment by RomainGoussault** [comment]
Ok thanks for the link.
