### ISSUE TITLE
Incorrect UCI output

### ISSUE THREAD

**Issue by tpoppins** [RomainGoussault/Deepov#51]
Deepov forgets to include "cp" after "score" in its UCI output. Because of that UCI-compliant GUIs (e.g. Cute Chess) display 0.00 as Deepov's eval for every move.

For example, Deepov outputs
`<Deepov(8): info depth 7 score 54 nodes 1107274 nps 1851628 time 598`
whereas it should be 
`<Deepov(8): info depth 7 score cp 54 nodes 1107274 nps 1851628 time 598`

Reference: [Problems parsing engine output](https://github.com/cutechess/cutechess/issues/406#issuecomment-407434284) issue in the Cute Chess repository.

**Comment by RomainGoussault** [comment]
Thanks, I will look into it.

**Comment by tpoppins** [comment]
I looked into it for you, the change is three chars in Search.cpp:485

`	std::cout << " score " << alpha;`
to
`	std::cout << " score cp " << alpha;`
